REM Generating build files...
cmake -DCMAKE_INSTALL_PREFIX:STRING=build -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE=Debug --no-warn-unused-cli -SC:/dev/Hara -Bc:/dev/Hara/build -G "Visual Studio 17 2022"

REM Building Stage application...
cmake --build c:/dev/Hara/build --config Debug --target ALL_BUILD -j 34 --

REM Launching Stage...
start %~dp0\..\..\build\stage\Debug\Stage.exe